# Generated by Django 5.2.17 on 2026-10-05 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('table', '0002_alter_resturanttable_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservationModel',
            new_name='Reservation',
        ),
    ]
